# Generated by Django 3.2.16 on 2023-04-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('detectionchoice', models.CharField(choices=[('WWeapon', 'Weapon'), ('IIntruder', 'Intruder')], default='WWeapon', max_length=10)),
                ('camsysname', models.CharField(max_length=50)),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
