# Generated by Django 3.2.16 on 2023-04-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='camsysname',
            field=models.CharField(choices=[('iVCam', [(1280, 720), (640, 480), (1280, 720), (640, 480), (1280, 720), (640, 480)]), ('Integrated Webcam', [(640, 480), (640, 360), (320, 240), (424, 240), (320, 180), (160, 120), (848, 480), (960, 540), (1280, 720), (848, 480), (960, 540), (1280, 720)])], default=('iVCam', [(1280, 720), (640, 480), (1280, 720), (640, 480), (1280, 720), (640, 480)]), max_length=50),
        ),
    ]
