# Generated by Django 3.2.16 on 2023-04-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_alter_camera_camsysname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='camsysname',
            field=models.CharField(choices=[('iVCam', 'iVCam'), ('Integrated Webcam', 'Integrated Webcam')], default=('iVCam', 'iVCam'), max_length=50),
        ),
    ]
