# Generated by Django 3.2.16 on 2023-04-05 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_alter_camera_camsysname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='camsysname',
            new_name='cam_sys_name',
        ),
        migrations.RenameField(
            model_name='camera',
            old_name='detectionchoice',
            new_name='detection_choice',
        ),
    ]
