# Generated by Django 3.2.16 on 2023-04-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_auto_20230405_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='detection_choice',
            field=models.CharField(choices=[('Weapon', 'Weapon'), ('Intruder', 'Intruder')], default='Weapon', max_length=10),
        ),
    ]
