# Generated by Django 3.2.16 on 2023-04-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_alter_camera_detection_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='cam_sys_name',
            field=models.CharField(choices=[('iVCam', 'iVCam'), ('Integrated Webcam', 'Integrated Webcam')], default='None', max_length=50),
        ),
    ]
