# Generated by Django 3.2.16 on 2023-04-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0006_alter_camera_cam_sys_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='cam_sys_name',
            field=models.CharField(choices=[('iVCam', 'iVCam'), ('Integrated Webcam', 'Integrated Webcam')], default=('iVCam', 'iVCam'), max_length=50),
        ),
        migrations.AlterField(
            model_name='camera',
            name='detection_choice',
            field=models.CharField(choices=[('Weapon', 'Weapon'), ('Intruder', 'Intruder')], default='None', max_length=10),
        ),
    ]
