# Generated by Django 4.0 on 2023-05-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0008_alter_camera_detection_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='cam_sys_name',
            field=models.CharField(choices=[('iVCam', 'iVCam'), ('Integrated Webcam', 'Integrated Webcam')], default=('iVCam', 'iVCam'), max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
