# Generated by Django 4.0 on 2023-05-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0009_alter_camera_cam_sys_name_alter_camera_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='cam_sys_name',
            field=models.CharField(choices=[('iVCam', 'iVCam'), ('Integrated Webcam', 'Integrated Webcam')], default=('iVCam', 'iVCam'), error_messages={'required': 'Camera already exists.'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(error_messages={'required': 'Name already exists.'}, max_length=50, unique=True),
        ),
    ]
